### ISSUE TITLE
Unable to close Anki program; forced to use task manager

### ISSUE THREAD

**Issue by RonilPatel7** [Arthur-Milchior/anki-Multiple-Windows#5]
Debug info:
Anki 2.1.24 (359b9f5c) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 7
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-05-04 14:08:05

Caught exception:
Traceback (most recent call last):
File "aqt\main.py", line 973, in closeEvent
File "aqt\main.py", line 436, in unloadProfileAndExit
File "aqt\main.py", line 411, in unloadProfile
File "aqt\main.py", line 519, in unloadCollection
File "aqt\main.py", line 783, in closeAllWindows
File "C:\Users\Ronil Patel\AppData\Roaming\Anki2\addons21\354407385\__init__.py", line 124, in closeAll
return super().closeAll(onsuccess)
File "aqt\__init__.py", line 122, in closeAll
RuntimeError: wrapped C/C++ object of type AdvancedBrowser has been deleted

This error appeared after using Add on number: 1126950429 & 1672832404

**Comment by Arthur-Milchior** [comment]
I do not expect that those two add-ons are related in anyway to the problem.
Sadly, there is very little I can do with it. It occurs rarely to me, but sometime python believes a window is opened while it's closed. Anki is not shipped with correct tools to detect this error, and checking whether a window actually closed is something too complex to add to an add-on. In this case, the window try to close, fails because it's already closed, and there is little I can do to ensure it's really closed. I can't assume that if there is an error while closing it's because the window is closed either, there may be other error source

**Comment by RonilPatel7** [comment]
Thank you for your message; I just upgraded to version 2.1.25 and the bug/error went away
